project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users import views

urlpatterns = [
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.Landing.as_view(), name='landing'),
    # url(r'^', include('registration.backends.default.urls')),
    # url(r'^messages/', include('postman.urls', namespace='postman')),
]

users/urls.py
from django.conf.urls import url
from users import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^landing$', views.Landing.as_view(), name='landing'),
    url(r'^register$', views.Register.as_view(), name='register'),
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^logout$', views.Logout.as_view(), name='logout'),
    url(r'^index$', views.Index.as_view(), name='index'),
    url(r'^show/(?P<profile_id>[0-9]+)$', views.Show.as_view(), name='show'),
    url(r'^profile$', views.Profile.as_view(), name='profile'),
    # url(r'^upload$', views.ProfileImageView.as_view(), name='profileimage'),
    url(r'^userprefandmatch$', views.UserPrefAndMatch.as_view(), name='userprefandmatch'),

]
# add static file location to use media as static file in production
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    # image is url string
    image = models.TextField(default='https://www.google.com/logos/doodles/2016/phoebe-snetsingers-85th-birthday-5179281716019200-hp.gif')
    gender = models.CharField(max_length=10, default='Female')


class UserFoodPref(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    is_peanut = models.BooleanField(default=False)
    is_vegetarian = models.BooleanField(default=False)
    is_vegan = models.BooleanField(default=False)
    is_lactose = models.BooleanField(default=False)
    is_diabetic = models.BooleanField(default=False)
    is_gluten = models.BooleanField(default=False)
    is_kosher = models.BooleanField(default=False)
    is_alcohol = models.BooleanField(default=False)


class UserMatchPref(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    match_peanut = models.BooleanField(default=False)
    match_vegetarian = models.BooleanField(default=False)
    match_vegan = models.BooleanField(default=False)
    match_lactose = models.BooleanField(default=False)
    match_diabetic = models.BooleanField(default=False)
    match_gluten = models.BooleanField(default=False)
    match_kosher = models.BooleanField(default=False)
    match_alcohol = models.BooleanField(default=False)


class Messages(models.Model):
    # null=True sets all reference objects to null when from_user is deleted
    # two foreign keys need a related_name attribute
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='message_from')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='message_to')
    msg_body = models.TextField()
    created = models.DateField(default=timezone.now)
    # users are not blocked by default, will have to write views logic when user is blocked
    blocked_user = models.BooleanField(default=False)


class Save(models.Model):
    # user who cliked save
    # two foreign keys need a related_name attribute
    user_who_saved = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='save_user_who_saved')
    saved_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='save_saved_user')


# hiding/blocking users
class Hidden(models.Model):
    # two foreign keys need a related_name attribute
    # if Tina 'hides' Kevin in her mathces, Kevin is hidden from Tina's list (hidden_from)
    hidden_from_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='hidden_from_user')
    # Subsequently, Tina is hidden "to" Kevin
    hidden_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='hidden_to')

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from .models import UserProfile, UserFoodPref, UserMatchPref
# from .forms import ProfileImageForm
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
# from django.core.mail import send_mail
# from django.db.models import Q
# import requests


# Create your views here.
class Landing(View):
    template_name = "users/landing.html"

    def get(self, request):
        print("In landing get")
        return render(request, self.template_name)


class Register(View):
    template_name = "users/register.html"
    # template_name = "accounts/activate.html"
    index = "users/index.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        valid_username = User.objects.filter(
            username=username
        )
        if len(valid_username) > 0:
            return JsonResponse({'Error': 'Username is taken. Please choose another username'})
        user = User.objects.create_user(
            username=username,
            email=email,
            password=password
        )
        default_choices = {
            'is_vegan': False,
            'is_peanut': False,
            'is_vegetarian': False,
            'is_lactose': False,
            'is_diabetic': False,
            'is_gluten': False,
            'is_kosher': False,
            'is_alcohol': False
        }
        match_choices = {
            'match_vegan': False,
            'match_peanut': False,
            'match_vegetarian': False,
            'match_lactose': False,
            'match_diabetic': False,
            'match_gluten': False,
            'match_kosher': False,
            'match_alcohol': False
        }

        UserFoodPref.objects.create(user=user, **default_choices)
        UserMatchPref.objects.create(user=user, **match_choices)
        UserProfile.objects.create(user=user)
        # users/index will redirect to users/users index
        # /users/index sends to index
        return redirect('/users/login')


class Login(View):
    template_name = "users/login.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        print(username, password)
        print("user is authenticate")
        print(user)
        if user:
            print("In user")
            request.session['username'] = username
            login(request, user)
            return redirect('/users/index')
        else:
            return JsonResponse({'status': 'Invalid username and/or password'})


class Show(View):
    template_name = "users/show.html"

    def get(self, request, profile_id=1):
        current_user = request.user
        profile = UserProfile.objects.get(id=profile_id)
        context = {
            'current_user': current_user,
            'profile': profile
        }
        return render(request, self.template_name, context)


class Index(View):
    template_name = "users/index.html"

    def get(self, request):
        user = request.user
        # index will blow up if the user doesn't have a match pref
        # will write a script to cover it but just in case the script doesn't work
        # the below will ensure index will continue to run
        default_own_pref = {
            'is_peanut': False,
            'is_vegetarian': False,
            'is_vegan': False,
            'is_lactose': False,
            'is_diabetic': False,
            'is_gluten': False,
            'is_kosher': False,
            'is_alcohol': False,
        }

        default_match_prefs = {
            'match_peanut': False,
            'match_vegetarian': False,
            'match_vegan': False,
            'match_lactose': False,
            'match_diabetic': False,
            'match_gluten': False,
            'match_kosher': False,
            'match_alcohol': False,
        }
        # below is done in case seed_db_with_users script fails
        # get or create expects kwargs and returns a tuple
        user_own_prefs, _ = UserFoodPref.objects.get_or_create(
            user=user,
            defaults=default_own_pref
        )

        user_match_prefs, _ = UserMatchPref.objects.get_or_create(
            user=user,
            defaults=default_match_prefs
        )

        # all of user's match pref is another user's foodprefs
        # use kwargs as filter
        user_match_prefs = UserMatchPref.objects.filter(user=user)
        user_own_prefs = UserFoodPref.objects.filter(user=user)

        own_pref = user_own_prefs.__dict__
        match_dict = user_match_prefs.__dict__
        print(match_dict)
        match = {}
        for key, value in match_dict.items():
            if "match_" in key and value == True:
                # key is something like 'match_vegan'
                # when the match_vegan is added to the match dict
                # it has the transformed key but the value remains the same
                new_key = key.replace('match', 'is')
                match[new_key] = True

        matching_food_prefs = UserFoodPref.objects.filter(**match)
        matching_users = [food_pref.user for food_pref in matching_food_prefs]
        # message = message.objects.all()
        # print(message)
        print(matching_users)
        matching_profiles = [UserProfile.objects.get(user=u) for u in matching_users] # all matching_profiles where the profile exists in matching_user
        matches = []
        for profile in matching_profiles:
            matches.append({
                'id': profile.id,
                'image': profile.image,
                'gender': profile.gender,
                'username': profile.user.username,
            })
        context = {
            'username': user.username,
            # since match is a list of dictionaries
            # have to use list comprehension to get the user out
            'matches': matches,
            # 'message': message,
        }
        return render(request, self.template_name, context)


class Profile(View):
    template_name = "users/profile.html"

    def get(self, request):
        # need to get the user's preferences first
        # get from database then put into context
        user = request.user
        user_own_prefs = UserFoodPref.objects.get(user=user)
        user_match_prefs = UserMatchPref.objects.get(user=user)
        own_pref = user_own_prefs.__dict__
        match_dict = user_match_prefs.__dict__
        print(own_pref)
        print(match_dict)
        context = own_pref.copy()
        context.update(match_dict)


        # import pdb; pdb.set_trace()
        return render(request, self.template_name, context)


# class ProfileImageView(View):
#     template_name = 'users/profileimage.html'
#     form_class = ProfileImageForm

#     def form_valid(self, form):
#         profile_image = ProfileImage(
#             # gets all kwargs that was passed in during the post
#             # every post has post and files dictionary in the request
#             # post has form data
#             # files has biniary data, either manipulate or save
#             # to get image, need to get file dictionary from kwargs
#             image=self.get_form_kwargs().get('files')['image'])
#         profile_image.save()
#         self.id = profile_image.id
#         return redirect(self.template_name)


class Logout(View):
    template_name = 'users/logout.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        logout(request)
        return redirect('/users/logout')


class UserPrefAndMatch(View):
    """
    When a user puts in their own food restrictions
    its saved in the database
    """

    def post(self, request):
        # We get a request from the user that includes their new user pref choices
        # We want to save it to the userfoodpref table for the user
        print(request.POST)
        # Here is the user
        user = request.user
        print('user', user)
        # user2 = User.objects.get(id=user.id)
        # import pdb; pdb.set_trace()
        # Here we get the user's existing prefs fom DB
        user_own_prefs = UserFoodPref.objects.get(user=user)
        user_match_prefs = UserMatchPref.objects.get(user=user)
        # Here are the new choices the user is sending us
        keys = request.POST.keys()
        choices_dict = {
            'is_vegan': False,
            'is_peanut': False,
            'is_vegetarian': False,
            'is_lactose': False,
            'is_diabetic': False,
            'is_gluten': False,
            'is_kosher': False,
            'is_alcohol': False
        }
        match_dict = {
            'match_vegan': False,
            'match_peanut': False,
            'match_vegetarian': False,
            'match_lactose': False,
            'match_diabetic': False,
            'match_gluten': False,
            'match_kosher': False,
            'match_alcohol': False
        }

        for choice in keys: # ['is_peanut', 'match_vegan']
            if "csrf" not in choice:
                # Is it a 'match_' string?
                if "match" in choice:
                    match_dict[choice] = True
                if "is_" in choice:
                    choices_dict[choice] = True

        print(choices_dict)
        user_own_prefs.__dict__.update(**choices_dict)
        user_match_prefs.__dict__.update(**match_dict)
        user_own_prefs.save()
        user_match_prefs.save()
        # import pdb; pdb.set_trace()
        return redirect('/users/index')

users/templates/users/index.html
{% extends 'base.html' %}
<!-- might have to relocate to the main app -->

{% block head %}
<title>Piki Main</title>
{% endblock %}

{% block content %}
<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <font color="black"<a class="navbar-brand page-scroll" href="#page-top">Piki</a></font>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'users:index' %}">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'users:profile'%}">{{user}}'s Profile</a>
                    </li>
<!--                      <li>
                        <a class="page-scroll" href="#services">Choices</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
<br>
<br>
<br>
<!-- <p>Currently signed in as: {{user}}</p> -->

<!-- <button action="{% url 'users:logout' %}" class='logoutbutton'>Logout</button>

<button action ="{% url 'users:profile' %}"class='profilebutton'>Profile</button> -->
<!-- on profile click, goes to profile where they can put in a bio and check boxs of dietary stuff -->
<!-- create click event for button click -->
<h3>Below are your matches! Piki away!</h3>

<ul>
	{% for match in matches %}
	<li class="user_profile">
		<a href="show/{{match.id}}">
			<h4 class="username">{{match.username}}</h4>
			<span class="gender">{{match.gender}}</span>
			<img class="avatar" src="{{match.image}}"/>
		</a>
	</li>
    {% endfor %}
</ul>

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block content%}

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <font color="black"<a class="navbar-brand page-scroll" href="#page-top">Piki</a></font>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'users:landing' %}">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'users:register' %}">Register</a>
                    </li>
<!--                      <li>
                        <a class="page-scroll" href="#services">Choices</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<h3> I'm logging in, I want the world to know, got to let it show</h3>
<br>
<form input="text" class="login" method="POST">
	<input type="text" name="username">Username</input>
	<input type="password" name="password">Password</input>
	{% csrf_token %}
	<button>
		Login
	</button>
</form>


{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% block content %}
<p>Sorry to see you go! Come back soon.
<br>
	<a href="{% url 'users:landing' %}">Login</a></p>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile Page</title>
<style type="text/css">
	body{
		padding-left: 3em;
	}
</style>
{% endblock %}

{% block content %}
<h3>I am...</h3>
<div id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <font color="black"<a class="navbar-brand page-scroll" href="#page-top">Piki</a></font>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'users:index' %}">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'users:profile'%}">{{user}}'s Profile</a>
                    </li>
<!--                      <li>
                        <a class="page-scroll" href="#services">Choices</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</div>
<h3>I am ...</h3>
<form action="{% url 'users:userprefandmatch' %}" name="UserPref" class="UserPref" method="POST">

	<input type="checkbox" class="is_alcohol" label for="is_alcohol" name="is_alcohol" {% if is_alcohol %}checked{% endif %}>Alcohol Free (does not drink alcohol)</label>
	<br>
	<input type="checkbox" class="is_peanut" label for="is_peanut" name="is_peanut" {% if is_peanut %}checked{% endif %}>Allergic to Peanuts</label>
	<br>
	<input type="checkbox" class="is_diabetic" label for="is_diabetic" name="is_diabetic" {% if is_diabetic %}checked{% endif %}>Diabetic </label>
	<br>
	<input type="checkbox" class="is_gluten" label for="is_gluten" name="is_gluten" {% if is_gluten %}checked{% endif %}>Gluten Free </label>
	<br>
	<input type="checkbox" class="is_kosher" label for="is_kosher" name="is_kosher" {% if is_kosher %}checked{% endif %}>Kosher</label>
	<br>
	<input type="checkbox" class="is_lactose" label for="is_lactose" name="is_lactose" {% if is_lactose %}checked{% endif %}>Lactose Intolerant</label>
	<br>
	<input type="checkbox" class="is_vegan" label for="is_vegan" name="is_vegan" {% if is_vegan %}checked{% endif %}>Vegan</label>
	<br>
	<input type="checkbox" class="is_vegetarian" label for="is_vegetarian" name="is_vegetarian" {% if is_vegan %}checked{% endif %}>Vegetarian</label>

	<h3>I am looking for someone who is...</h3>

	<input type="checkbox" class="match_alcohol" label for="match_alcohol" name="match_alcohol" {% if match_alcohol %}checked{% endif %}>Alcohol Free (does not drink alcohol)</label>
	<br>
	<input type="checkbox" class="match_peanut" label for="match_peanut" name="match_peanut" {% if match_peanut %}checked{% endif %}>Allergic to Peanuts</label>
	<br>
	<input type="checkbox" class="match_diabetic" label for="match_diabetic" name="match_diabetic" {% if match_diabetic %}checked{% endif %}>Diabetic </label>
	<br>
	<input type="checkbox" class="match_gluten" label for="match_gluten" name="match_gluten" {% if match_gluten %}checked{% endif %}>Gluten Free </label>
	<br>
	<input type="checkbox" class="match_kosher" label for="match_kosher" name="match_kosher" {% if match_kosher %}checked{% endif %}>Kosher</label>
	<br>
	<input type="checkbox" class="match_lactose" label for="match_lactose" name="match_lactose" {% if match_lactose %}checked{% endif %}>Lactose Intolerant</label>
	<br>
	<input type="checkbox" class="match_vegan" label for="match_vegan" name="match_vegan" {% if match_vegan %}checked{% endif %}>Vegan</label>
	<br>
	<input type="checkbox" class="match_vegetarian" label for="match_vegetarian" name="match_vegetarian" {% if match_vegan %}checked{% endif %}>Vegetarian</label>

	<br><br>
	<input type="submit" input value="Show me matches!"></input>
	{% csrf_token %}
</form>
<br><br>

{% endblock %}

users/templates/users/profileimage.html
{% extends 'base.html' %}

{% block content %}
<!-- encode type tells the server on post that we're uploading data, without this we can't get binary data to the server -->
<form action="{% url 'users:profileimageview' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="submit" />
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block head %}
<title>Register</title>
{% endblock %}

{% block content %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Piki Me, Pikachu</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/magnific-popup.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <font color="black"<a class="navbar-brand page-scroll" href="#page-top">Piki</a></font>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'users:landing' %}">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'users:login' %}">Login</a>
                    </li>
<!--                      <li>
                        <a class="page-scroll" href="#services">Choices</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<h3>After all, it's register</h3>
<br>
<!-- <form class="form-inline">
  <div class="form-group">
	<form input="text" class="register" method="POST">
	<input type="text" placeholder="Username" name="username">Username</input>
	<input type="password" name="password"> placeholder="Password">Password</input>
	<input type="text" name="email" placeholder="Email" Email</input>
	{% csrf_token %}
	<button type="submit" class="btn btn-success">Register
	</button>
</form> -->
<center>
<br>
<br>
<br>
<br>
<br>
<form class="form-inline" method="POST" action="{% url 'users:register' %}">
    {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputName2">Username</label>
    <input type="text" name="username" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputName2" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Email</label>
    <input type="email" class="form-control" name="email" id="exampleInputEmail2" placeholder="jane.doe@example.com">
  </div>
  <button type="submit" class="btn btn-primary">Register</button>
</form>
<br>
    <small class="text-muted">Please check your email for your registration link. We'll never share your email with anyone else.</small>
</center>
{% endblock %}

users/templates/users/show.html
{% extends 'base.html' %}
<!-- might have to relocate to the main app -->

{% block head %}
<title>Piki Main</title>
{% endblock %}

{% block content %}
<div id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <font color="black"<a class="navbar-brand page-scroll" href="#page-top">Piki</a></font>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'users:index' %}">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'users:profile'%}">{{user}}'s Profile</a>
                    </li>
<!--                      <li>
                        <a class="page-scroll" href="#services">Choices</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</div>
<br>
<br>
<br>


<a href="/users/index">Back to Index</a>
<section id="page-top">
	Hello from: {{profile_id}}
	<img src="{{profile.image}}">
	{{profile.user.username}}
	<a href="/messages/write/" button type="button" class="btn btn-secondary">Message</button>


</section>


{% endblock %}